[project]
name = "badnerf"
version = "1.0.0"

dependencies=[
    "nerfstudio>=1.0.0",
    "pypose"
]

# black
[tool.black]
line-length = 120

# pylint
[tool.pylint.messages_control]
max-line-length = 120
generated-members = ["numpy.*", "torch.*", "cv2.*", "cv.*"]

[tool.setuptools.packages.find]
include = ["badnerf"]

[project.entry-points.'nerfstudio.dataparser_configs']
badnerf-data = 'badnerf.badnerf_config_dataparser:BadNerfDataparser'

[project.entry-points.'nerfstudio.method_configs']
badnerf_nerfacto = 'badnerf.badnerf_config_method:badnerf_nerfacto'
